### PR TITLE
Add API for incrementally writing archives

### PR DESCRIPTION
**Pull request by dexgs**
To resolve duplicated code, `add_file` is now backed by
`start_new_file`, `append_data_store`, `append_data_deflate`,
and `finish_file`.

`write_data_store`, `write_data_deflate`, and the `buf` field
of`Archive` have been removed.

### CODE REVIEW

**Comment by illdefined** [comment]
@yu-re-ka Is there any reason to not merge this PR?

**Comment by dexgs** [comment]
If you merge it, please merge #3 first as the changes here are applied after the changes made in that PR. I originally had all the commits in one PR but broke it up into 3 upon request.

**Comment by yu-re-ka** [comment]
I am not fully happy with the API because the user can cause a panic in the library code by trying to append data before calling `start_file`. Returning some kind of FileWriter struct from `start_file` could improve the API so that the user can not create a DoS issue in their application.
For the zip64 feature I thought it would maybe be better to keep the complexity low by always creating zip64 archives.

But I probably won't be able to work on this any time soon, so I merged the current versions of the PRs and published a new version, 0.5.0.

Fell free to submit new PRs for implementing the suggestions above.

Thanks again for your contributions and sorry for taking so long to respond!

**Comment by dexgs** [comment]
Would it be acceptable to just replace the `unwrap` with returning an error in the case of calling append when an entry in the archive hasn't been properly started?

I agree that having to manually set Zip64 is a bit unwieldy, but enforcing it would break compatibility with some Zip implementations. What about enforcing Zip64 by default and removing the option from the existing API, but adding additional functions where the feature can be explicitly turned on and off?

**Pull request merged**
